### ISSUE TITLE
Add a `getAltitude` method 

### ISSUE THREAD

**Issue by siddacious** [adafruit/Adafruit_DPS310#3]
The DPS310 appears to be quite a good sensor for an altimeter, however there isn't currently any method included in the library to get altitude directly.

This code from the BMP280 should be easy to adapt:
https://github.com/adafruit/Adafruit_BMP280_Library/blob/a49542c69d134c180c45622d1c2da7d030fbbe88/Adafruit_BMP280.cpp#L373

**Comment by ladyada** [comment]
@caternuson wanna PR? its the same code as any other sensor

**Comment by caternuson** [comment]
@ladyada Yep. Mouse was on the SUBMIT button. :)

**Comment by ladyada** [comment]
merged!

**Comment by caternuson** [comment]
closed!
(fixed with #4 )
