### ISSUE TITLE
BitOrder Has Not Been Declared

### ISSUE THREAD

**Issue by k-dunc** [adafruit/Adafruit_DPS310#5]
- Arduino board:  Raspberry Pi connected to the DPS310

- Arduino IDE version (found in Arduino -> About Arduino menu):  1.8.13

I have a DPS310 wired to my Raspberry Pi, and I'm using this library in order to communicate with it. Simply grabbing the code in the Example directory and attempting to compile it in a new Sketch yields the following errors:

    In file included from C:\Documents\Arduino\libraries\Adafruit_BusIO/Adafruit_BusIO_Register.h:2,
    from C:\Documents\Arduino\libraries\Adafruit_DPS310/Adafruit_DPS310.h:17,
    from C:\Documents\Arduino\DPS310_example\DPS310_example.ino:3:
    C:\Documents\Arduino\libraries\Adafruit_BusIO/Adafruit_SPIDevice.h:62:22: error: 'BitOrder' has not been declared
    BitOrder dataOrder = SPI_BITORDER_MSBFIRST,
    ^~~~~~~~
    C:\Documents\Arduino\libraries\Adafruit_BusIO/Adafruit_SPIDevice.h:67:22: error: 'BitOrder' has not been declared
    BitOrder dataOrder = SPI_BITORDER_MSBFIRST,
    ^~~~~~~~
    C:\Documents\Arduino\libraries\Adafruit_BusIO/Adafruit_SPIDevice.h:88:3: error: 'BitOrder' does not name a type
    BitOrder _dataOrder;
    ^~~~~~~~
    exit status 1
    Error compiling for board RaspberryPI B+/2.

Any ideas on what the issue may be?

Thanks kindly.

**Comment by ladyada** [comment]
how are you compiling for raspberry pi  in arduino ide???

**Comment by k-dunc** [comment]
Hi @ladyada, 

Thanks for your question. Long story short: I first wrote a Python program using the DPS310 Python library, but realised that it did not provide support for Altitude - which was most of the reason why I purchased this sensor. I'm only very new at this sort of thing, so correct me if I'm wrong, but I then followed [this tutorial](https://youtu.be/lZvhtfUlY8Y) to link the Arduino IDE to the Raspberry Pi. I then took the 'dps310_simpletest' example code from this repo and attempted to compile it, and that's when I got the error messages above.

**Comment by ladyada** [comment]
huh i think you're like the first person to ever try to do this with our libraries! let me see if i can install the arduino cli on a raspberry pi to replicate

**Comment by ladyada** [comment]
ok i looked at it, that implementation is really incomplete and old...it just wont work. 
you'll be better off just grabbing an online calculation for altitude from pressure and not using arduino-for-pi
https://github.com/adafruit/Adafruit_Learning_System_Guides/blob/24ad4e86c41dcb9e10babb477f7ca941f6609d85/CLUE_Altimeter/clue_altimeter.py#L88

**Comment by caternuson** [comment]
This seems solved and closed, but it's tied to a forum post I've been tracking.

For this:
> I first wrote a Python program using the DPS310 Python library, but realised that it did not provide support for Altitude

curious what library that was? The current Python library has it:
https://github.com/adafruit/Adafruit_CircuitPython_DPS310/blob/9474a6fbc3df30af134c9943e8db57bb18c9e6c2/adafruit_dps310.py#L291

Here's info on using the DPS310 with the Pi:
https://learn.adafruit.com/adafruit-dps310-precision-barometric-pressure-sensor/python-circuitpython#python-computer-wiring-3054772-4
