### ISSUE TITLE
Unneeded call to TwosComplement

### ISSUE THREAD

**Issue by DRNadler** [adafruit/Adafruit_DPS310#6]
For coefficients declared int16_t, the call to twosComplement does nothing, as the sign bit is already in the MSB:
`int16_t _c0, _c1, _c01, _c11, _c20, _c21, _c30;`
In the lines starting here, that call can be replaced with a cast to int16_t:
https://github.com/adafruit/Adafruit_DPS310/blob/d5c072457b0d209485755d9996a49bc8e3b278ea/Adafruit_DPS310.cpp#L210

Hope that helps!
Now if only I could figure out why my sensor is not working...

**Comment by ladyada** [comment]
well no harm done :)
