### ISSUE TITLE
dps310 pressure sensor high precision mode (2cm)

### ISSUE THREAD

**Issue by mintisan** [adafruit/Adafruit_DPS310#8]
Any examples about high precision mode feature ？

"The DPS310 sensor from Infineon a high-precision barometric sensor, perfect for measuring altitude changes with a up to ±0.002 hPa (or ±0.02 m) precision high precision mode and ± 1 hPa absolute accuracy."

**Comment by ladyada** [comment]
looks like you just have to set oversampling to 64x

![image](https://github.com/adafruit/Adafruit_DPS310/assets/1214161/92df03da-2708-48ba-b09c-3c50806727af)

which we do in the examples
https://github.com/adafruit/Adafruit_DPS310/blob/master/examples/dps310_simpletest/dps310_simpletest.ino#L22
